// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AppointmentStatus string

const (
	AppointmentStatusScheduled AppointmentStatus = "Scheduled"
	AppointmentStatusCompleted AppointmentStatus = "Completed"
	AppointmentStatusCancelled AppointmentStatus = "Cancelled"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type Company struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Position struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Reserf struct {
	ID        int64
	UserID    sql.NullInt64
	ServiceID sql.NullInt64
	Datetime  time.Time
	Status    AppointmentStatus
	CreatedAt time.Time
}

type Service struct {
	ID              int64
	StudioID        sql.NullInt64
	Name            string
	Description     sql.NullString
	DurationMinutes int32
	CreatedAt       time.Time
}

type ServicePrice struct {
	ID        int64
	ServiceID sql.NullInt64
	Price     string
	ValidFrom time.Time
	ValidTo   sql.NullTime
}

type Staff struct {
	ID         int64
	StudioID   sql.NullInt64
	UserID     sql.NullInt64
	PositionID sql.NullInt64
	CreatedAt  time.Time
}

type Studio struct {
	ID        int64
	CityID    sql.NullInt64
	AdminID   sql.NullInt64
	CompanyID sql.NullInt64
	Name      string
	Address   string
	CreatedAt time.Time
}
