// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addAppointments = `-- name: AddAppointments :exec
INSERT INTO appointments (
    user_id,
    service_id,
    datetime
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (user_id,service_id,datetime) DO NOTHING
`

type AddAppointmentsParams struct {
	UserID    sql.NullInt64
	ServiceID sql.NullInt64
	Datetime  time.Time
}

func (q *Queries) AddAppointments(ctx context.Context, arg AddAppointmentsParams) error {
	_, err := q.db.ExecContext(ctx, addAppointments, arg.UserID, arg.ServiceID, arg.Datetime)
	return err
}
