// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addReserves = `-- name: AddReserves :exec
INSERT INTO reserves (
    user_id,
    service_id,
    datetime
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (user_id, service_id, datetime) DO NOTHING
`

type AddReservesParams struct {
	UserID    sql.NullInt64
	ServiceID sql.NullInt64
	Datetime  time.Time
}

func (q *Queries) AddReserves(ctx context.Context, arg AddReservesParams) error {
	_, err := q.db.ExecContext(ctx, addReserves, arg.UserID, arg.ServiceID, arg.Datetime)
	return err
}
